### ISSUE TITLE
用作插件时报错，大佬帮忙给看看

### ISSUE THREAD

**Issue by fgo000000** [cc004/autopcr#29]
[2023-06-13 11:12:11,107 nonebot] ERROR: Failed to import "hoshino.modules.autopcr.clan_unlocker", error: No module named 'autopcr'
[2023-06-13 11:12:11,107 nonebot] ERROR: No module named 'autopcr'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 263, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\mali\HoshinoBot\hoshino\modules\autopcr\clan_unlocker.py", line 1, in <module>
    from autopcr.core import pcrclient, ApiException, sessionmgr
ModuleNotFoundError: No module named 'autopcr'
[2023-06-13 11:12:11,107 nonebot] ERROR: Failed to import "hoshino.modules.autopcr.httpserver_test", error: No module named 'autopcr'
[2023-06-13 11:12:11,107 nonebot] ERROR: No module named 'autopcr'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 263, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\mali\HoshinoBot\hoshino\modules\autopcr\httpserver_test.py", line 1, in <module>
    from autopcr.http_server.httpserver_test import *
ModuleNotFoundError: No module named 'autopcr'
[2023-06-13 11:12:11,122 nonebot] ERROR: Failed to import "hoshino.modules.autopcr.main", error: No module named 'autopcr'
[2023-06-13 11:12:11,122 nonebot] ERROR: No module named 'autopcr'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 263, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\mali\HoshinoBot\hoshino\modules\autopcr\main.py", line 3, in <module>
    import autopcr
ModuleNotFoundError: No module named 'autopcr'
[2023-06-13 11:12:14,030 nonebot] ERROR: Failed to import "hoshino.modules.autopcr.server", error: cannot import name 'PUBLIC_ADDRESS' from 'hoshino.config' (C:\Users\Administrator\Desktop\mali\HoshinoBot\hoshino\config\__init__.py)
[2023-06-13 11:12:14,030 nonebot] ERROR: cannot import name 'PUBLIC_ADDRESS' from 'hoshino.config' (C:\Users\Administrator\Desktop\mali\HoshinoBot\hoshino\config\__init__.py)
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 263, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\mali\HoshinoBot\hoshino\modules\autopcr\server.py", line 18, in <module>
    from hoshino.config import PUBLIC_ADDRESS
ImportError: cannot import name 'PUBLIC_ADDRESS' from 'hoshino.config' (C:\Users\Administrator\Desktop\mali\HoshinoBot\hoshino\config\__init__.py)

**Comment by cc004** [comment]
更新hoshino配置文件到新版格式
