### ISSUE TITLE
已经git了最新的hos，用作插件版报错。

### ISSUE THREAD

**Issue by hibiki233** [cc004/autopcr#42]
ERROR: Failed to import and load "hoshino.modules.autopcr.clan_iterator", error: No module named 'autopcr'
[2023-07-12 13:22:05,766 nonebot] ERROR: No module named 'autopcr'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\HoshinoBot\hoshino\modules\autopcr\clan_iterator.py", line 1, in <module>
    from autopcr.model.requests import *
ModuleNotFoundError: No module named 'autopcr'
[2023-07-12 13:22:05,766 nonebot] ERROR: Failed to import and load "hoshino.modules.autopcr.clan_unlocker", error: No module named 'autopcr'
[2023-07-12 13:22:05,766 nonebot] ERROR: No module named 'autopcr'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\HoshinoBot\hoshino\modules\autopcr\clan_unlocker.py", line 1, in <module>
    from autopcr.core import pcrclient, ApiException, sessionmgr
ModuleNotFoundError: No module named 'autopcr'
[2023-07-12 13:22:05,782 nonebot] ERROR: Failed to import and load "hoshino.modules.autopcr.db_test", error: No module named 'autopcr'
[2023-07-12 13:22:05,782 nonebot] ERROR: No module named 'autopcr'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\HoshinoBot\hoshino\modules\autopcr\db_test.py", line 1, in <module>
    from autopcr.db.assetmgr import instance as assetmgr
ModuleNotFoundError: No module named 'autopcr'
[2023-07-12 13:22:05,782 nonebot] ERROR: Failed to import and load "hoshino.modules.autopcr.httpserver_test", error: No module named 'autopcr'
[2023-07-12 13:22:05,782 nonebot] ERROR: No module named 'autopcr'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\HoshinoBot\hoshino\modules\autopcr\httpserver_test.py", line 1, in <module>
    from autopcr.http_server.httpserver_test import *
ModuleNotFoundError: No module named 'autopcr'
[2023-07-12 13:22:05,813 nonebot] ERROR: Failed to import and load "hoshino.modules.autopcr.server", error: cannot import name 'PUBLIC_ADDRESS' from 'hoshino.config' (C:\HoshinoBot\hoshino\config\__init__.py)
[2023-07-12 13:22:05,813 nonebot] ERROR: cannot import name 'PUBLIC_ADDRESS' from 'hoshino.config' (C:\HoshinoBot\hoshino\config\__init__.py)
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\HoshinoBot\hoshino\modules\autopcr\server.py", line 18, in <module>
    from hoshino.config import PUBLIC_ADDRESS
ImportError: cannot import name 'PUBLIC_ADDRESS' from 'hoshino.config' (C:\HoshinoBot\hoshino\config\__init__.py)
[2023-07-12 13:22:05,813 nonebot] INFO: Succeeded to import and load "hoshino.modules.autopcr.util"
C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

**Comment by cc004** [comment]
你没更新配置文件
